###
POST http://localhost:8081/api/urls
Content-Type: text/plain
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdGVwaGVud2IxIiwiaWF0IjoxNzc3MDg1OTExLCJleHAiOjE3NzcxNzIzMTF9.YL4GH7A-nYif3zdY4PXPDo3L5eWXLdAIkFvSWbA2-aU

https://www.youtube.com/watch?v=dQw4w9WgXcQ
###
GET http://localhost:8081/r/aadd673

###
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{"username": "stephenwb1", "email": "stephenwb360@gmail.com", "password": "abcd1234"}

###
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{"username": "stephenwb1", "password": "abcd1234"}